CREATE DATABASE IF NOT EXISTS alx_book_store;
USE alx_book_store;

CREATE TABLE AUTHORS (
  AUTHOR_ID INT PRIMARY KEY,
  AUTHOR_NAME VARCHAR(215) NOT NULL
) ENGINE=INNODB;

CREATE TABLE BOOKS (
  BOOK_ID INT PRIMARY KEY,
  TITLE VARCHAR(130) NOT NULL,
  AUTHOR_ID INT NOT NULL,
  PRICE DOUBLE,
  PUBLICATION_DATE DATE,
  CONSTRAINT FK_BOOKS_AUTHORS FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
) ENGINE=INNODB;

CREATE TABLE CUSTOMERS (
  CUSTOMER_ID INT PRIMARY KEY,
  CUSTOMER_NAME VARCHAR(215) NOT NULL,
  EMAIL VARCHAR(215),
  ADDRESS TEXT
) ENGINE=INNODB;

CREATE TABLE ORDERS (
  ORDER_ID INT PRIMARY KEY,
  CUSTOMER_ID INT NOT NULL,
  ORDER_DATE DATE,
  CONSTRAINT FK_ORDERS_CUSTOMERS FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
) ENGINE=INNODB;

CREATE TABLE ORDER_DETAILS (
  ORDERDETAILID INT PRIMARY KEY,
  ORDER_ID INT NOT NULL,
  BOOK_ID INT NOT NULL,
  QUANTITY DOUBLE,
  CONSTRAINT FK_ORDERDETAILS_ORDERS FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
  CONSTRAINT FK_ORDERDETAILS_BOOKS FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
) ENGINE=INNODB;
